// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections.Generic;
using Leap;
using Sculpt;


public abstract class ManipulationHandTool : HandTool
{

	protected TargetObjectScript tos;


	public int vertexWithMaxDistance = 0;
	public float maxDistanceFromHit = 0.0f;
	protected Sculpter sculpter;
	protected SculptMesh sculptMesh;
	public Ray ray;
	public float minDistance;



	protected List<int> iVertsSelected = new List<int>();
	protected List<int> iTrisSelected = new List<int>();

	public override void Start()
	{	
		Debug.Log("Manipulation tool started");
		base.Start();
		sculpter = target.GetComponent<Sculpter>();
		sculptMesh = target.GetComponent<SculptMesh>();
	}




	public Ray CalculateRay(Leap.Vector pos){
		Leap.InteractionBox iBox = LeapInput.Frame.InteractionBox;
		Leap.Vector normalizedPosition = iBox.NormalizePoint(pos);
		Vector3 screenPos = new Vector3(UnityEngine.Screen.width * normalizedPosition.x,
		                                UnityEngine.Screen.height * normalizedPosition.y,
		                                0.0f);
		ray = Camera.main.ScreenPointToRay (screenPos);
		return ray;
	}
}

