// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;

namespace Sculpt
{
	public class Geometry
	{
		public static void triangleNormal(Vector3 v1, Vector3 v2, Vector3 v3, out Vector3 normal){
			normal = (v1 + v2 + v3) / 3;
		}

		public static void triangleAabb(Vector3 v1, Vector3 v2, Vector3 v3, out Bounds aabb){
			aabb = new Bounds();
//			aabb.Encapsulate(v1);
//			aabb.Encapsulate(v2);
//			aabb.Encapsulate(v3);


			Vector3 min = Vector3.Min(v1, v2);
			min = Vector3.Min(min, v3);

			Vector3 max = Vector3.Min(v1, v2);
			max = Vector3.Max(max, v3);

//			Bounds aabb2 = new Bounds();
			aabb.SetMinMax(min, max);

			
		}

	}
}

