// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
namespace Sculpt{
	public class Vertex
	{
		public static long TagMask = 0;
		public static long SculptMask = 0;

		public int id;
		public long tagFlag;
		public long sculptFlag;
		public List<int> tIndices;
		public List<int> ringVertices;

		public Vertex (int id)
		{
			this.id = id;
			tIndices = new List<int>();
			ringVertices = new List<int>();
		}

		public Vertex copy(){
			Vertex newV = new Vertex(this.id);
			newV.tIndices = this.tIndices.ToList();
			newV.ringVertices = this.ringVertices.ToList();

			return newV;
		}
	}
}

